// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbE8OPdH6LoEgGAN8luIbR2-O-1Ka1mWQ',
    appId: '1:19531418982:web:774ca3668a186685b18ca7',
    messagingSenderId: '19531418982',
    projectId: 'flutter-fitness-app-ea9be',
    authDomain: 'flutter-fitness-app-ea9be.firebaseapp.com',
    storageBucket: 'flutter-fitness-app-ea9be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDub6C1GUhQtIRKCOLjniSUdtFCqPMVN3Q',
    appId: '1:19531418982:android:a4d59d35588da790b18ca7',
    messagingSenderId: '19531418982',
    projectId: 'flutter-fitness-app-ea9be',
    storageBucket: 'flutter-fitness-app-ea9be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAjx__6HucC7z4GwiXRKa0GR6eIrhG1vQ',
    appId: '1:19531418982:ios:2a67013b2c5c0782b18ca7',
    messagingSenderId: '19531418982',
    projectId: 'flutter-fitness-app-ea9be',
    storageBucket: 'flutter-fitness-app-ea9be.firebasestorage.app',
    androidClientId: '19531418982-425cbuqe1b4b6shjqtsvv2kivberp9mi.apps.googleusercontent.com',
    iosClientId: '19531418982-glndmfjseqtbe86od1233ibf6hms9fgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAjx__6HucC7z4GwiXRKa0GR6eIrhG1vQ',
    appId: '1:19531418982:ios:2a67013b2c5c0782b18ca7',
    messagingSenderId: '19531418982',
    projectId: 'flutter-fitness-app-ea9be',
    storageBucket: 'flutter-fitness-app-ea9be.firebasestorage.app',
    androidClientId: '19531418982-425cbuqe1b4b6shjqtsvv2kivberp9mi.apps.googleusercontent.com',
    iosClientId: '19531418982-glndmfjseqtbe86od1233ibf6hms9fgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbE8OPdH6LoEgGAN8luIbR2-O-1Ka1mWQ',
    appId: '1:19531418982:web:8797af57869f2c07b18ca7',
    messagingSenderId: '19531418982',
    projectId: 'flutter-fitness-app-ea9be',
    authDomain: 'flutter-fitness-app-ea9be.firebaseapp.com',
    storageBucket: 'flutter-fitness-app-ea9be.firebasestorage.app',
  );
}
